syntax = "proto3";
package side.farming;

import "gogoproto/gogo.proto";
import "google/protobuf/duration.proto";
import "cosmos/base/v1beta1/coin.proto";
import "cosmos_proto/cosmos.proto";

option go_package = "github.com/sideprotocol/side/x/farming/types";

// Asset defines the farming asset
message Asset {
    // Asset denom
    string denom = 1;
    // Ratio of the reward relative to the total rewards
    string reward_ratio = 2 [
      (cosmos_proto.scalar)  = "cosmos.Dec",
      (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
      (gogoproto.nullable)   = false
    ];
    // Minimum staking amount
    string min_staking_amount = 3 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
}

// Params defines the parameters for the module.
message Params {
  bool enabled = 1;
  google.protobuf.Duration epoch_duration = 2 [(gogoproto.nullable) = false, (gogoproto.stdduration) = true];
  cosmos.base.v1beta1.Coin reward_per_epoch = 3 [(gogoproto.nullable) = false];
  repeated google.protobuf.Duration lock_durations = 4 [(gogoproto.nullable) = false, (gogoproto.stdduration) = true];
  repeated Asset eligible_assets = 5 [(gogoproto.nullable) = false];
}
