syntax = "proto3";
package side.auction;

import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "cosmos/base/v1beta1/coin.proto";

option go_package = "github.com/sideprotocol/side/x/auction/types";

message Bid {
    uint64 id = 1;
    uint64 auction_id = 2;
    string bidder = 3;
    int64 bid_price = 4;
    cosmos.base.v1beta1.Coin bid_amount = 5 [
        (gogoproto.nullable)     = false,
        (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins"
    ];
    cosmos.base.v1beta1.Coin bidded_amount = 6 [
        (gogoproto.nullable)     = false,
        (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins"
    ];
    BidStatus status = 7;
}

message Auction {
    uint64 id = 1;
    string loan_id = 2;
    string borrower = 3;
    string agency = 4;
    cosmos.base.v1beta1.Coin deposited_asset = 5 [
        (gogoproto.nullable)     = false,
        (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coin"
    ];
    int64 liquidated_price = 6;
    google.protobuf.Timestamp liquidated_time = 7 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
    cosmos.base.v1beta1.Coin expected_value = 8 [
        (gogoproto.nullable)     = false,
        (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coin"
    ];
    cosmos.base.v1beta1.Coin bidded_value = 9 [
        (gogoproto.nullable)     = false,
        (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coin"
    ];
    int64 bidded_amount = 10;
    string liquidation_cet = 11;
    string payment_tx = 12;
    string payment_tx_id = 13;
    AuctionStatus status = 14;
}

enum AssetType {
    ASSET_TYPE_BITCOIN = 0;
}

enum AuctionStatus {
    AUCTION_STATUS_UNSPECIFIED = 0;
    AUCTION_STATUS_OPEN = 1;
    AUCTION_STATUS_CLOSED = 2;
    AUCTION_STATUS_SETTLED = 3;
}

enum BidStatus {
    BID_STATUS_UNSPECIFIED = 0;
    BID_STATUS_BIDDING = 1;
    BID_STATUS_ACCEPTED = 2;
    BID_STATUS_REJECTED = 3;
    BID_STATUS_CANCELLED = 4;
}
