syntax = "proto3";
package side.lending;

import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "cosmos/base/v1beta1/coin.proto";
import "side/btcbridge/btcbridge.proto";

option go_package = "github.com/sideprotocol/side/x/lending/types";

// Status options for a lending pool
enum PoolStatus {
    INACTIVE = 0;
    ACTIVE = 1;
}

// Lending pool config
message PoolConfig {
    // supply rate permille
    uint32 supply_rate = 1;
    // borrow rate permille
    uint32 borrow_rate = 2;
    // reserve factor permille
    uint32 reserve_factor = 3;
    // supply cap
    string supply_cap = 4 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // borrow cap
    string borrow_cap = 5 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // debt ceiling
    string debt_ceiling = 6 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // origination fee
    string origination_fee = 7 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // maximum loan to value permille
    uint32 ltv = 8;
    // liquidation ltv permille
    uint32 liquidation_threshold = 9;
    // liquidation penalty permille
    uint32 liquidation_penalty = 10;
}

message LendingPool {
    string id = 1;
    cosmos.base.v1beta1.Coin supply = 2 [
      (gogoproto.nullable)     = false,
      (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coin"
    ];
    string available_amount = 3 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string borrowed_amount = 4 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string total_shares = 5 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    PoolConfig config = 6 [(gogoproto.nullable) = false];
    PoolStatus status = 7;
}

// Loan Status
enum LoanStatus {
    // Unspecified
    Unspecified = 0;
    // Loan Requested
    Requested = 1;
    // Loan Open
    Open = 2;
    // Loan Rejected
    Rejected = 3;
    // Loan Cancelled
    Cancelled = 4;
    // Loan Repaid
    Repaid = 5;
    // Loan Defaulted
    Defaulted = 6;
    // Loan Liquidated
    Liquidated = 7;
    // Loan Closed
    Closed = 8;
}

message Loan {
    string vault_address = 1; // id
    string borrower = 2;
    string borrowerPubKey = 3;
    string agency = 4;
    int64 maturity_time = 5;
    int64 final_timeout = 6;
    cosmos.base.v1beta1.Coin borrow_amount = 7 [(gogoproto.nullable) = false];
    string origination_fee = 8 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string interest = 9 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string protocol_fee = 10 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string term = 11 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    uint64 liquidation_event_id = 12;
    uint64 default_liquidation_event_id = 13;
    uint64 repayment_event_id = 14;
    uint64 attestation_id = 15;
    repeated string deposit_txs = 16;
    string collateral_amount = 17 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string pool_id = 18;
    uint64 auction_id = 19;
    google.protobuf.Timestamp create_at = 20 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
    LoanStatus status = 21;
}

enum CetType {
  LIQUIDATION = 0;
  DEFAULT_LIQUIDATION = 1;
  REPAYMENT = 2;
}

message CetInfo {
  uint64 event_id = 1;
  uint32 outcome_index = 2;
  string signature_point = 3;
  string script = 4;
}

message LiquidationCet {
  string tx = 1;
  repeated string borrower_adaptor_signatures = 2;
  repeated string borrower_adapted_signatures = 3;
  repeated string agency_signatures = 4;
  string signed_tx_hex = 5;
}

message RepaymentCet {
  string tx = 1;
  repeated string agency_adaptor_signatures = 2;
  repeated string agency_adapted_signatures = 3;
  repeated string borrower_signatures = 4;
  string signed_tx_hex = 5;
}

message DLCMeta {
    LiquidationCet liquidation_cet = 1 [(gogoproto.nullable) = false]; 
    LiquidationCet default_liquidation_cet = 2 [(gogoproto.nullable) = false];
    RepaymentCet repayment_cet = 3 [(gogoproto.nullable) = false];
    repeated side.btcbridge.UTXO vault_utxos = 4;
    string internal_key = 5;
    string multisig_script = 6;
    string timeout_refund_script = 7;
}

message DepositLog {
    string txid = 2;
    string vault_address = 1;
    string deposit_tx = 3;
} 

message Repayment {
    string loan_id = 1;
    string txid = 2;
    string tx = 3;
    string adaptor_point = 4;
    repeated string dca_adaptor_signatures = 5;
    string dca_adapted_signature = 6;
    google.protobuf.Timestamp create_at = 7 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
}

message Cancellation {
    string loan_id = 1;
    string txid = 2;
    string tx = 3;
    repeated string signatures = 4; 
    repeated string dca_signatures = 5;
    google.protobuf.Timestamp create_at = 6 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
}