syntax = "proto3";
package side.lending;

import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "cosmos/base/v1beta1/coin.proto";
import "side/btcbridge/btcbridge.proto";

option go_package = "github.com/sideprotocol/side/x/lending/types";

// Status options for a lending pool
enum PoolStatus {
    INACTIVE = 0;
    ACTIVE = 1;
    PAUSED = 2;
}

// Lending pool config
message PoolConfig {
    // borrow apr permille
    uint32 borrow_apr = 1 [(gogoproto.customname) = "BorrowAPR"];
    // reserve factor permille
    uint32 reserve_factor = 2;
    // supply cap
    string supply_cap = 3 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // borrow cap
    string borrow_cap = 4 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // debt ceiling
    string debt_ceiling = 5 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // minimum amount to be borrowed
    string min_borrow_amount = 6 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // origination fee
    string origination_fee = 7 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    // maximum ltv percent
    uint32 max_ltv = 8;
    // liquidation ltv percent
    uint32 liquidation_threshold = 9;
    // indicates if the pool is paused
    bool paused = 10;
}

message LendingPool {
    string id = 1;
    cosmos.base.v1beta1.Coin supply = 2 [
      (gogoproto.nullable) = false
    ];
    string available_amount = 3 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string total_borrowed = 4 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string total_reserves = 5 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    cosmos.base.v1beta1.Coin total_stokens = 6 [
      (gogoproto.nullable) = false,
      (gogoproto.customname) = "TotalSTokens"
    ];
    PoolConfig config = 7 [(gogoproto.nullable) = false];
    PoolStatus status = 8;
}

// Loan Status
enum LoanStatus {
    // Unspecified
    Unspecified = 0;
    // Loan Requested
    Requested = 1;
    // Loan Open
    Open = 2;
    // Loan Rejected
    Rejected = 3;
    // Loan Cancelled
    Cancelled = 4;
    // Loan Repaid
    Repaid = 5;
    // Loan Defaulted
    Defaulted = 6;
    // Loan Liquidated
    Liquidated = 7;
    // Loan Closed
    Closed = 8;
}

message Loan {
    string vault_address = 1; // id
    string borrower = 2;
    string borrowerPubKey = 3;
    string dcm = 4 [(gogoproto.customname) = "DCM"];
    int64 maturity_time = 5;
    int64 final_timeout = 6;
    string pool_id = 7;
    cosmos.base.v1beta1.Coin borrow_amount = 8 [(gogoproto.nullable) = false];
    string origination_fee = 9 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string interest = 10 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    string protocol_fee = 11 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    int64 term = 12;
    string liquidation_price = 13 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    uint64 liquidation_event_id = 14;
    uint64 default_liquidation_event_id = 15;
    uint64 repayment_event_id = 16;
    repeated string deposit_txs = 17;
    string collateral_amount = 18 [
      (gogoproto.customtype) = "cosmossdk.io/math.Int",
      (gogoproto.nullable) = false
    ];
    uint64 liquidation_id = 19;
    google.protobuf.Timestamp create_at = 20 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
    LoanStatus status = 21;
}

enum CetType {
  LIQUIDATION = 0;
  DEFAULT_LIQUIDATION = 1;
  REPAYMENT = 2;
}

message CetInfo {
  uint64 event_id = 1;
  uint32 outcome_index = 2;
  string signature_point = 3;
  string script = 4;
}

message LiquidationCet {
  string tx = 1;
  repeated string borrower_adaptor_signatures = 2;
  repeated string borrower_adapted_signatures = 3;
  repeated string dcm_signatures = 4 [(gogoproto.customname) = "DCMSignatures"];
  string signed_tx_hex = 5;
}

message RepaymentCet {
  string tx = 1;
  repeated string dcm_adaptor_signatures = 2 [(gogoproto.customname) = "DCMAdaptorSignatures"];
  repeated string dcm_adapted_signatures = 3 [(gogoproto.customname) = "DCMAdaptedSignatures"];
  repeated string borrower_signatures = 4;
  string signed_tx_hex = 5;
}

message DLCMeta {
    LiquidationCet liquidation_cet = 1 [(gogoproto.nullable) = false]; 
    LiquidationCet default_liquidation_cet = 2 [(gogoproto.nullable) = false];
    RepaymentCet repayment_cet = 3 [(gogoproto.nullable) = false];
    repeated side.btcbridge.UTXO vault_utxos = 4;
    string internal_key = 5;
    string multisig_script = 6;
    string timeout_refund_script = 7;
}

message DepositLog {
    string txid = 1;
    string vault_address = 2;
    string deposit_tx = 3;
    bool verified = 4;
}

message Repayment {
    string loan_id = 1;
    cosmos.base.v1beta1.Coin amount = 2 [(gogoproto.nullable) = false];
    google.protobuf.Timestamp create_at = 3 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
}

message Cancellation {
    string loan_id = 1;
    string txid = 2;
    string tx = 3;
    repeated string signatures = 4;
    repeated string dcm_signatures = 5 [(gogoproto.customname) = "DCMSignatures"];
    google.protobuf.Timestamp create_at = 6 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
}