syntax = "proto3";
package side.lending;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "cosmos/base/v1beta1/coin.proto";
import "side/lending/params.proto";
import "side/lending/lending.proto";

option go_package = "github.com/sideprotocol/side/x/lending/types";

// Query defines the gRPC querier service.
service Query {
    // Params queries the parameters of the module.
    rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
      option (google.api.http).get = "/side/lending/params";
    }

    rpc Pool(QueryPoolRequest) returns (QueryPoolResponse) {
        option (google.api.http).get = "/side/lending/pool/{id}";
    }

    rpc Pools(QueryPoolsRequest) returns (QueryPoolsResponse) {
        option (google.api.http).get = "/side/lending/pools";
    }

    rpc PoolExchangeRate(QueryPoolExchangeRateRequest) returns (QueryPoolExchangeRateResponse) {
        option (google.api.http).get = "/side/lending/pool/exchange_rate";
    }

    rpc CollateralAddress(QueryCollateralAddressRequest) returns (QueryCollateralAddressResponse) {
        option (google.api.http).get = "/side/lending/collateral/address";
    }

    rpc LiquidationEvent(QueryLiquidationEventRequest) returns (QueryLiquidationEventResponse) {
        option (google.api.http).get = "/side/lending/liquidation/event";
    }

    rpc Loan(QueryLoanRequest) returns (QueryLoanResponse) {
        option (google.api.http).get = "/side/lending/loans/{loan_id}";
    }

    rpc Loans(QueryLoansRequest) returns (QueryLoansResponse) {
        option (google.api.http).get = "/side/lending/loans";
    }

    rpc LoansByAddress(QueryLoansByAddressRequest) returns (QueryLoansByAddressResponse) {
        option (google.api.http).get = "/side/lending/loans/address/{address}";
    }

    rpc LoanCetInfos(QueryLoanCetInfosRequest) returns (QueryLoanCetInfosResponse) {
        option (google.api.http).get = "/side/lending/loan/cet/infos";
    }

    rpc LoanDlcMeta(QueryLoanDlcMetaRequest) returns (QueryLoanDlcMetaResponse) {
        option (google.api.http).get = "/side/lending/loan/dlc/meta";
    }

    rpc LoanCancellation(QueryLoanCancellationRequest) returns (QueryLoanCancellationResponse) {
        option (google.api.http).get = "/side/lending/loan/cancellation";
    }

    rpc Repayment(QueryRepaymentRequest) returns (QueryRepaymentResponse) {
        option (google.api.http).get = "/side/lending/loan/repayment";
    }

    rpc CurrentInterest(QueryCurrentInterestRequest) returns (QueryCurrentInterestResponse) {
        option (google.api.http).get = "/side/lending/loan/current_interest";
    }
}

// QueryPoolRequest is request type for the Query/Pool RPC method.
message QueryPoolRequest {
    string id = 1;
}

// QueryPoolResponse is response type for the Query/Pool RPC method.
message QueryPoolResponse {
    LendingPool pool = 1;
}

// QueryPoolsRequest is request type for the Query/Pools RPC method.
message QueryPoolsRequest {
    cosmos.base.query.v1beta1.PageRequest pagination = 1;
}

// QueryPoolsResponse is response type for the Query/Pools RPC method.
message QueryPoolsResponse {
    repeated LendingPool pools = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

// QueryPoolExchangeRateRequest is request type for the Query/PoolExchangeRate RPC method.
message QueryPoolExchangeRateRequest {
    string pool_id = 1;
}

// QueryPoolExchangeRateResponse is response type for the Query/PoolExchangeRate RPC method.
message QueryPoolExchangeRateResponse {
    string exchange_rate = 1;
}

message QueryLiquidationEventRequest {
    string pool_id = 1;
    string collateral_amount = 2;
    string borrow_amount = 3;
}

message QueryLiquidationEventResponse {
    uint64 event_id = 1;
    string oracle_pubkey = 2;
    string nonce = 3;
    string price = 4;
    string signature_point = 5;
}

message QueryLoanCetInfosRequest {
    string loan_id = 1;
    string collateral_amount = 2;
}

message QueryLoanCetInfosResponse {
    CetInfo liquidation_cet_info = 1;
    CetInfo default_liquidation_cet_info = 2;
    CetInfo repayment_cet_info = 3;
}

message QueryCollateralAddressRequest{
    string borrower_pubkey = 1;
    string agency_pubkey = 2;
    uint64 maturity_time = 3;
}

message QueryCollateralAddressResponse{
    string address = 1;
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {
}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
    Params params = 1 [(gogoproto.nullable) = false];
}

// QueryLoanRequest is request type for the Query/Loan RPC method.
message QueryLoanRequest {
    string loan_id = 1;
}

// QueryLoanResponse is response type for the Query/Loan RPC method.
message QueryLoanResponse {
    Loan loan = 1;
}

// QueryLoansRequest is request type for the Query/Loans RPC method.
message QueryLoansRequest {
    LoanStatus status = 1;
    cosmos.base.query.v1beta1.PageRequest pagination = 2;
}

// QueryLoansResponse is response type for the Query/Loans RPC method.
message QueryLoansResponse {
    repeated Loan loans = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

// QueryLoansByAddressRequest is request type for the Query/LoansByAddress RPC method.
message QueryLoansByAddressRequest {
    string address = 1;
    LoanStatus status = 2;
    cosmos.base.query.v1beta1.PageRequest pagination = 3;
}

// QueryLoansByAddressResponse is response type for the Query/LoansByAddress RPC method.
message QueryLoansByAddressResponse {
    repeated Loan loans = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

// QueryLoanDlcMetaRequest is request type for the Query/LoanDlcMeta RPC method.
message QueryLoanDlcMetaRequest {
    string loan_id = 1;
}

// QueryLoanDlcMetaResponse is response type for the Query/LoanDlcMeta RPC method.
message QueryLoanDlcMetaResponse {
    DLCMeta dlc_meta = 1;
}

// QueryLoanCancellationRequest is request type for the Query/LoanCancellation RPC method.
message QueryLoanCancellationRequest {
    string loan_id = 1;
}

// QueryLoanCancellationResponse is response type for the Query/LoanCancellation RPC method.
message QueryLoanCancellationResponse {
    Cancellation cancellation = 1;
}

message QueryRepaymentRequest {
    string loan_id = 1;
}

message QueryRepaymentResponse {
    Repayment repayment = 1;
}

message QueryCurrentInterestRequest {
    string loan_id = 1;
}

message QueryCurrentInterestResponse {
    cosmos.base.v1beta1.Coin interest = 1 [(gogoproto.nullable) = false];
}