syntax = "proto3";
package side.liquidation;

import "gogoproto/gogo.proto";
import "cosmos_proto/cosmos.proto";

option go_package = "github.com/sideprotocol/side/x/liquidation/types";

// Params defines the parameters for the module.
message Params {
    // minimum liquidation factor
    string min_liquidation_factor = 1 [
      (cosmos_proto.scalar)  = "cosmos.Dec",
      (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
      (gogoproto.nullable)   = false
    ];
    // liquidation bonus factor
    string liquidation_bonus_factor = 2 [
      (cosmos_proto.scalar)  = "cosmos.Dec",
      (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
      (gogoproto.nullable)   = false
    ];
    // protocol liquidation fee factor
    string protocol_liquidation_fee_factor = 3 [
      (cosmos_proto.scalar)  = "cosmos.Dec",
      (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
      (gogoproto.nullable)   = false
    ];
    // protocol liquidation fee collector
    string protocol_liquidation_fee_collector = 4;
}
