// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: side/liquidation/liquidation.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AssetType int32

const (
	AssetType_ASSET_TYPE_BITCOIN AssetType = 0
)

var AssetType_name = map[int32]string{
	0: "ASSET_TYPE_BITCOIN",
}

var AssetType_value = map[string]int32{
	"ASSET_TYPE_BITCOIN": 0,
}

func (x AssetType) String() string {
	return proto.EnumName(AssetType_name, int32(x))
}

func (AssetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_095b2bff8d803d3e, []int{0}
}

type LiquidationStatus int32

const (
	LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED LiquidationStatus = 0
	LiquidationStatus_LIQUIDATION_STATUS_LIQUIDATING LiquidationStatus = 1
	LiquidationStatus_LIQUIDATION_STATUS_LIQUIDATED  LiquidationStatus = 2
	LiquidationStatus_LIQUIDATION_STATUS_SETTLING    LiquidationStatus = 3
	LiquidationStatus_LIQUIDATION_STATUS_SETTLED     LiquidationStatus = 4
)

var LiquidationStatus_name = map[int32]string{
	0: "LIQUIDATION_STATUS_UNSPECIFIED",
	1: "LIQUIDATION_STATUS_LIQUIDATING",
	2: "LIQUIDATION_STATUS_LIQUIDATED",
	3: "LIQUIDATION_STATUS_SETTLING",
	4: "LIQUIDATION_STATUS_SETTLED",
}

var LiquidationStatus_value = map[string]int32{
	"LIQUIDATION_STATUS_UNSPECIFIED": 0,
	"LIQUIDATION_STATUS_LIQUIDATING": 1,
	"LIQUIDATION_STATUS_LIQUIDATED":  2,
	"LIQUIDATION_STATUS_SETTLING":    3,
	"LIQUIDATION_STATUS_SETTLED":     4,
}

func (x LiquidationStatus) String() string {
	return proto.EnumName(LiquidationStatus_name, int32(x))
}

func (LiquidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_095b2bff8d803d3e, []int{1}
}

// Signing intent
type SigningIntent int32

const (
	SigningIntent_SIGNING_INTENT_DEFAULT SigningIntent = 0
)

var SigningIntent_name = map[int32]string{
	0: "SIGNING_INTENT_DEFAULT",
}

var SigningIntent_value = map[string]int32{
	"SIGNING_INTENT_DEFAULT": 0,
}

func (x SigningIntent) String() string {
	return proto.EnumName(SigningIntent_name, int32(x))
}

func (SigningIntent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_095b2bff8d803d3e, []int{2}
}

type Liquidation struct {
	Id                           uint64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanId                       string                      `protobuf:"bytes,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Debtor                       string                      `protobuf:"bytes,3,opt,name=debtor,proto3" json:"debtor,omitempty"`
	DCM                          string                      `protobuf:"bytes,4,opt,name=dcm,proto3" json:"dcm,omitempty"`
	CollateralAmount             types.Coin                  `protobuf:"bytes,5,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount"`
	ActualCollateralAmount       types.Coin                  `protobuf:"bytes,6,opt,name=actual_collateral_amount,json=actualCollateralAmount,proto3" json:"actual_collateral_amount"`
	DebtAmount                   types.Coin                  `protobuf:"bytes,7,opt,name=debt_amount,json=debtAmount,proto3" json:"debt_amount"`
	LiquidatedPrice              cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=liquidated_price,json=liquidatedPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidated_price"`
	LiquidatedTime               time.Time                   `protobuf:"bytes,9,opt,name=liquidated_time,json=liquidatedTime,proto3,stdtime" json:"liquidated_time"`
	LiquidatedCollateralAmount   types.Coin                  `protobuf:"bytes,10,opt,name=liquidated_collateral_amount,json=liquidatedCollateralAmount,proto3" json:"liquidated_collateral_amount"`
	LiquidatedDebtAmount         types.Coin                  `protobuf:"bytes,11,opt,name=liquidated_debt_amount,json=liquidatedDebtAmount,proto3" json:"liquidated_debt_amount"`
	LiquidationBonusAmount       types.Coin                  `protobuf:"bytes,12,opt,name=liquidation_bonus_amount,json=liquidationBonusAmount,proto3" json:"liquidation_bonus_amount"`
	ProtocolLiquidationFee       types.Coin                  `protobuf:"bytes,13,opt,name=protocol_liquidation_fee,json=protocolLiquidationFee,proto3" json:"protocol_liquidation_fee"`
	UnliquidatedCollateralAmount types.Coin                  `protobuf:"bytes,14,opt,name=unliquidated_collateral_amount,json=unliquidatedCollateralAmount,proto3" json:"unliquidated_collateral_amount"`
	LiquidationCet               string                      `protobuf:"bytes,15,opt,name=liquidation_cet,json=liquidationCet,proto3" json:"liquidation_cet,omitempty"`
	SettlementTx                 string                      `protobuf:"bytes,16,opt,name=settlement_tx,json=settlementTx,proto3" json:"settlement_tx,omitempty"`
	SettlementTxId               string                      `protobuf:"bytes,17,opt,name=settlement_tx_id,json=settlementTxId,proto3" json:"settlement_tx_id,omitempty"`
	Status                       LiquidationStatus           `protobuf:"varint,18,opt,name=status,proto3,enum=side.liquidation.LiquidationStatus" json:"status,omitempty"`
}

func (m *Liquidation) Reset()         { *m = Liquidation{} }
func (m *Liquidation) String() string { return proto.CompactTextString(m) }
func (*Liquidation) ProtoMessage()    {}
func (*Liquidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_095b2bff8d803d3e, []int{0}
}
func (m *Liquidation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Liquidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Liquidation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Liquidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Liquidation.Merge(m, src)
}
func (m *Liquidation) XXX_Size() int {
	return m.Size()
}
func (m *Liquidation) XXX_DiscardUnknown() {
	xxx_messageInfo_Liquidation.DiscardUnknown(m)
}

var xxx_messageInfo_Liquidation proto.InternalMessageInfo

func (m *Liquidation) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Liquidation) GetLoanId() string {
	if m != nil {
		return m.LoanId
	}
	return ""
}

func (m *Liquidation) GetDebtor() string {
	if m != nil {
		return m.Debtor
	}
	return ""
}

func (m *Liquidation) GetDCM() string {
	if m != nil {
		return m.DCM
	}
	return ""
}

func (m *Liquidation) GetCollateralAmount() types.Coin {
	if m != nil {
		return m.CollateralAmount
	}
	return types.Coin{}
}

func (m *Liquidation) GetActualCollateralAmount() types.Coin {
	if m != nil {
		return m.ActualCollateralAmount
	}
	return types.Coin{}
}

func (m *Liquidation) GetDebtAmount() types.Coin {
	if m != nil {
		return m.DebtAmount
	}
	return types.Coin{}
}

func (m *Liquidation) GetLiquidatedTime() time.Time {
	if m != nil {
		return m.LiquidatedTime
	}
	return time.Time{}
}

func (m *Liquidation) GetLiquidatedCollateralAmount() types.Coin {
	if m != nil {
		return m.LiquidatedCollateralAmount
	}
	return types.Coin{}
}

func (m *Liquidation) GetLiquidatedDebtAmount() types.Coin {
	if m != nil {
		return m.LiquidatedDebtAmount
	}
	return types.Coin{}
}

func (m *Liquidation) GetLiquidationBonusAmount() types.Coin {
	if m != nil {
		return m.LiquidationBonusAmount
	}
	return types.Coin{}
}

func (m *Liquidation) GetProtocolLiquidationFee() types.Coin {
	if m != nil {
		return m.ProtocolLiquidationFee
	}
	return types.Coin{}
}

func (m *Liquidation) GetUnliquidatedCollateralAmount() types.Coin {
	if m != nil {
		return m.UnliquidatedCollateralAmount
	}
	return types.Coin{}
}

func (m *Liquidation) GetLiquidationCet() string {
	if m != nil {
		return m.LiquidationCet
	}
	return ""
}

func (m *Liquidation) GetSettlementTx() string {
	if m != nil {
		return m.SettlementTx
	}
	return ""
}

func (m *Liquidation) GetSettlementTxId() string {
	if m != nil {
		return m.SettlementTxId
	}
	return ""
}

func (m *Liquidation) GetStatus() LiquidationStatus {
	if m != nil {
		return m.Status
	}
	return LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED
}

type LiquidationRecord struct {
	Id               uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LiquidationId    uint64     `protobuf:"varint,2,opt,name=liquidation_id,json=liquidationId,proto3" json:"liquidation_id,omitempty"`
	Liquidator       string     `protobuf:"bytes,3,opt,name=liquidator,proto3" json:"liquidator,omitempty"`
	DebtAmount       types.Coin `protobuf:"bytes,4,opt,name=debt_amount,json=debtAmount,proto3" json:"debt_amount"`
	CollateralAmount types.Coin `protobuf:"bytes,5,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount"`
	BonusAmount      types.Coin `protobuf:"bytes,6,opt,name=bonus_amount,json=bonusAmount,proto3" json:"bonus_amount"`
	Time             time.Time  `protobuf:"bytes,7,opt,name=time,proto3,stdtime" json:"time"`
}

func (m *LiquidationRecord) Reset()         { *m = LiquidationRecord{} }
func (m *LiquidationRecord) String() string { return proto.CompactTextString(m) }
func (*LiquidationRecord) ProtoMessage()    {}
func (*LiquidationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_095b2bff8d803d3e, []int{1}
}
func (m *LiquidationRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationRecord.Merge(m, src)
}
func (m *LiquidationRecord) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationRecord proto.InternalMessageInfo

func (m *LiquidationRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LiquidationRecord) GetLiquidationId() uint64 {
	if m != nil {
		return m.LiquidationId
	}
	return 0
}

func (m *LiquidationRecord) GetLiquidator() string {
	if m != nil {
		return m.Liquidator
	}
	return ""
}

func (m *LiquidationRecord) GetDebtAmount() types.Coin {
	if m != nil {
		return m.DebtAmount
	}
	return types.Coin{}
}

func (m *LiquidationRecord) GetCollateralAmount() types.Coin {
	if m != nil {
		return m.CollateralAmount
	}
	return types.Coin{}
}

func (m *LiquidationRecord) GetBonusAmount() types.Coin {
	if m != nil {
		return m.BonusAmount
	}
	return types.Coin{}
}

func (m *LiquidationRecord) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func init() {
	proto.RegisterEnum("side.liquidation.AssetType", AssetType_name, AssetType_value)
	proto.RegisterEnum("side.liquidation.LiquidationStatus", LiquidationStatus_name, LiquidationStatus_value)
	proto.RegisterEnum("side.liquidation.SigningIntent", SigningIntent_name, SigningIntent_value)
	proto.RegisterType((*Liquidation)(nil), "side.liquidation.Liquidation")
	proto.RegisterType((*LiquidationRecord)(nil), "side.liquidation.LiquidationRecord")
}

func init() {
	proto.RegisterFile("side/liquidation/liquidation.proto", fileDescriptor_095b2bff8d803d3e)
}

var fileDescriptor_095b2bff8d803d3e = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xc7, 0xe3, 0x34, 0xa4, 0xdb, 0x97, 0x36, 0xeb, 0x8e, 0x56, 0xc1, 0xcd, 0x2e, 0x4e, 0x69,
	0x85, 0x88, 0x8a, 0xb0, 0xe9, 0x72, 0x41, 0xe2, 0x42, 0x12, 0xbb, 0x95, 0x51, 0x36, 0x5b, 0x6c,
	0xe7, 0x50, 0x84, 0x64, 0x39, 0xf6, 0x6c, 0xd6, 0xc2, 0xf6, 0x84, 0x78, 0x8c, 0xda, 0x0f, 0x81,
	0xb4, 0x1f, 0x86, 0x3b, 0xd7, 0x3d, 0xae, 0x38, 0x21, 0x0e, 0x05, 0xb5, 0x5f, 0x82, 0x23, 0x1a,
	0x3b, 0x5e, 0x4f, 0x1b, 0x76, 0xe5, 0x4a, 0xdc, 0x3c, 0x6f, 0xfe, 0xef, 0xf7, 0x66, 0xde, 0xbc,
	0xf7, 0x0c, 0x07, 0x49, 0xe0, 0x63, 0x35, 0x0c, 0x7e, 0x4a, 0x03, 0xdf, 0xa5, 0x01, 0x89, 0xf9,
	0x6f, 0x65, 0xb1, 0x24, 0x94, 0x20, 0x91, 0x69, 0x14, 0xce, 0xde, 0x7d, 0x34, 0x27, 0x73, 0x92,
	0x6d, 0xaa, 0xec, 0x2b, 0xd7, 0x75, 0x7b, 0x73, 0x42, 0xe6, 0x21, 0x56, 0xb3, 0xd5, 0x2c, 0x7d,
	0xa1, 0xd2, 0x20, 0xc2, 0x09, 0x75, 0xa3, 0xc5, 0x4a, 0x20, 0x7b, 0x24, 0x89, 0x48, 0xa2, 0xce,
	0xdc, 0x04, 0xab, 0x3f, 0x1f, 0xcf, 0x30, 0x75, 0x8f, 0x55, 0x8f, 0x04, 0xab, 0x40, 0xdd, 0xbd,
	0x7c, 0xdf, 0xc9, 0xc9, 0xf9, 0x22, 0xdf, 0x3a, 0xf8, 0x65, 0x0b, 0x5a, 0xe3, 0xf2, 0x04, 0xa8,
	0x0d, 0xf5, 0xc0, 0x97, 0x84, 0x7d, 0xa1, 0xdf, 0x30, 0xeb, 0x81, 0x8f, 0x3e, 0x84, 0xcd, 0x90,
	0xb8, 0xb1, 0x13, 0xf8, 0x52, 0x7d, 0x5f, 0xe8, 0x6f, 0x99, 0x4d, 0xb6, 0x34, 0x7c, 0xd4, 0x81,
	0xa6, 0x8f, 0x67, 0x94, 0x2c, 0xa5, 0x8d, 0xdc, 0x9e, 0xaf, 0xd0, 0x1e, 0x6c, 0xf8, 0x5e, 0x24,
	0x35, 0x98, 0x71, 0xb8, 0x79, 0x7d, 0xd5, 0xdb, 0xd0, 0x46, 0xcf, 0x4c, 0x66, 0x43, 0x63, 0xd8,
	0xf5, 0x48, 0x18, 0xba, 0x14, 0x2f, 0xdd, 0xd0, 0x71, 0x23, 0x92, 0xc6, 0x54, 0xfa, 0x60, 0x5f,
	0xe8, 0xb7, 0x9e, 0xee, 0x29, 0xab, 0x53, 0xb1, 0x2b, 0x28, 0xab, 0x2b, 0x28, 0x23, 0x12, 0xc4,
	0xc3, 0xc6, 0xeb, 0xab, 0x5e, 0xcd, 0x14, 0x4b, 0xcf, 0x41, 0xe6, 0x88, 0xce, 0x41, 0x72, 0x3d,
	0x9a, 0xba, 0xa1, 0xb3, 0x0e, 0x6d, 0x56, 0x83, 0x76, 0x72, 0xc0, 0xe8, 0x2e, 0xfa, 0x1b, 0x68,
	0xb1, 0xdb, 0x14, 0xb4, 0xcd, 0x6a, 0x34, 0x60, 0x3e, 0x2b, 0xc2, 0x0f, 0x20, 0x16, 0xef, 0x8a,
	0x7d, 0x67, 0xb1, 0x0c, 0x3c, 0x2c, 0x3d, 0xc8, 0x52, 0x72, 0xcc, 0xb4, 0x7f, 0x5e, 0xf5, 0x1e,
	0xe7, 0xb4, 0xc4, 0xff, 0x51, 0x09, 0x88, 0x1a, 0xb9, 0xf4, 0xa5, 0x32, 0xc6, 0x73, 0xd7, 0xbb,
	0xd4, 0xb0, 0xf7, 0xfb, 0xaf, 0x9f, 0xc3, 0x2a, 0x98, 0x86, 0x3d, 0xf3, 0x61, 0x89, 0x3a, 0x63,
	0x24, 0xf4, 0x0c, 0x38, 0x93, 0xc3, 0xaa, 0x41, 0xda, 0xca, 0xce, 0xd8, 0x55, 0xf2, 0x52, 0x51,
	0x8a, 0x52, 0x51, 0xec, 0xa2, 0x54, 0x86, 0x0f, 0x58, 0xe0, 0x57, 0x7f, 0xf5, 0x04, 0xb3, 0x5d,
	0x3a, 0xb3, 0x6d, 0xe4, 0xc2, 0x13, 0x0e, 0xb7, 0x9e, 0x4d, 0xa8, 0x76, 0xff, 0x6e, 0x09, 0x59,
	0xcb, 0xe8, 0x14, 0x3a, 0x5c, 0x08, 0x3e, 0xb9, 0xad, 0x6a, 0xf0, 0x47, 0xa5, 0xbb, 0x56, 0xa6,
	0xf9, 0x1c, 0x24, 0xae, 0x7d, 0x9c, 0x19, 0x89, 0xd3, 0xa4, 0x00, 0x6f, 0x57, 0xac, 0x01, 0x0e,
	0x30, 0x64, 0xfe, 0x25, 0x3a, 0x4b, 0xa2, 0x47, 0x42, 0x87, 0x8f, 0xf1, 0x02, 0x63, 0x69, 0xa7,
	0x22, 0xba, 0x00, 0x70, 0x0d, 0x76, 0x82, 0x31, 0xc2, 0x20, 0xa7, 0xf1, 0x7b, 0x33, 0xde, 0xae,
	0x16, 0xe0, 0x09, 0x8f, 0x59, 0xcb, 0xf9, 0xa7, 0x65, 0x95, 0xb0, 0x83, 0x7b, 0x98, 0x4a, 0x0f,
	0xb3, 0x56, 0x6d, 0x73, 0xe6, 0x11, 0xa6, 0xe8, 0x10, 0x76, 0x12, 0x4c, 0x69, 0x88, 0x23, 0x1c,
	0x53, 0x87, 0x5e, 0x48, 0x62, 0x26, 0xdb, 0x2e, 0x8d, 0xf6, 0x05, 0xea, 0x83, 0x78, 0x4b, 0xc4,
	0x26, 0xc2, 0x6e, 0x8e, 0xe3, 0x75, 0x86, 0x8f, 0xbe, 0x86, 0x66, 0x42, 0x5d, 0x9a, 0x26, 0x12,
	0xda, 0x17, 0xfa, 0xed, 0xa7, 0x87, 0xca, 0xdd, 0x39, 0xa7, 0x70, 0x09, 0xb1, 0x32, 0xa9, 0xb9,
	0x72, 0x39, 0xf8, 0xa7, 0x0e, 0xbb, 0xdc, 0xae, 0x89, 0x3d, 0xb2, 0xf4, 0xd7, 0xa6, 0xd2, 0x27,
	0xc0, 0xdf, 0xa1, 0x18, 0x4e, 0x0d, 0x73, 0x87, 0xb3, 0x1a, 0x3e, 0x92, 0x01, 0x0a, 0xc3, 0xdb,
	0x39, 0xc5, 0x59, 0xee, 0xf6, 0x79, 0xe3, 0xfe, 0x7d, 0xfe, 0xff, 0x8e, 0xb4, 0x21, 0x6c, 0xdf,
	0x2a, 0xe1, 0x8a, 0x63, 0xac, 0x35, 0xe3, 0xea, 0xf6, 0x2b, 0x68, 0x64, 0x03, 0x61, 0xf3, 0x1e,
	0x03, 0x21, 0xf3, 0x38, 0x3a, 0x84, 0xad, 0x41, 0x92, 0x60, 0x6a, 0x5f, 0x2e, 0x30, 0xea, 0x00,
	0x1a, 0x58, 0x96, 0x6e, 0x3b, 0xf6, 0xf9, 0x99, 0xee, 0x0c, 0x0d, 0x7b, 0xf4, 0xdc, 0x98, 0x88,
	0xb5, 0xa3, 0xdf, 0x84, 0x5b, 0xef, 0x93, 0xbf, 0x1e, 0x3a, 0x00, 0x79, 0x6c, 0x7c, 0x37, 0x35,
	0xb4, 0x81, 0x6d, 0x3c, 0x9f, 0x38, 0x96, 0x3d, 0xb0, 0xa7, 0x96, 0x33, 0x9d, 0x58, 0x67, 0xfa,
	0xc8, 0x38, 0x31, 0x74, 0x4d, 0xac, 0xbd, 0x43, 0xf3, 0xd6, 0x34, 0x39, 0x15, 0x05, 0xf4, 0x31,
	0x7c, 0xf4, 0x1e, 0x8d, 0xae, 0x89, 0x75, 0xd4, 0x83, 0xc7, 0xff, 0x21, 0xb1, 0x74, 0xdb, 0x1e,
	0x33, 0xc6, 0x06, 0x92, 0xa1, 0xfb, 0x2e, 0x81, 0xae, 0x89, 0x8d, 0xa3, 0xcf, 0x60, 0xc7, 0x0a,
	0xe6, 0x71, 0x10, 0xcf, 0x8d, 0x98, 0xe2, 0x98, 0xa2, 0x2e, 0x74, 0x2c, 0xe3, 0x74, 0x62, 0x4c,
	0x4e, 0x1d, 0x63, 0x62, 0xeb, 0x13, 0xdb, 0xd1, 0xf4, 0x93, 0xc1, 0x74, 0x6c, 0x8b, 0xb5, 0xe1,
	0xb7, 0xaf, 0xaf, 0x65, 0xe1, 0xcd, 0xb5, 0x2c, 0xfc, 0x7d, 0x2d, 0x0b, 0xaf, 0x6e, 0xe4, 0xda,
	0x9b, 0x1b, 0xb9, 0xf6, 0xc7, 0x8d, 0x5c, 0xfb, 0xfe, 0x8b, 0x79, 0x40, 0x5f, 0xa6, 0x33, 0xc5,
	0x23, 0x91, 0xca, 0xea, 0xbb, 0xe8, 0xf5, 0x6c, 0xa1, 0x5e, 0xdc, 0xfa, 0xf5, 0xd3, 0xcb, 0x05,
	0x4e, 0x66, 0xcd, 0x4c, 0xf2, 0xe5, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x56, 0x0f, 0x8e,
	0x1b, 0x08, 0x00, 0x00,
}

func (m *Liquidation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Liquidation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Liquidation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.SettlementTxId) > 0 {
		i -= len(m.SettlementTxId)
		copy(dAtA[i:], m.SettlementTxId)
		i = encodeVarintLiquidation(dAtA, i, uint64(len(m.SettlementTxId)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.SettlementTx) > 0 {
		i -= len(m.SettlementTx)
		copy(dAtA[i:], m.SettlementTx)
		i = encodeVarintLiquidation(dAtA, i, uint64(len(m.SettlementTx)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.LiquidationCet) > 0 {
		i -= len(m.LiquidationCet)
		copy(dAtA[i:], m.LiquidationCet)
		i = encodeVarintLiquidation(dAtA, i, uint64(len(m.LiquidationCet)))
		i--
		dAtA[i] = 0x7a
	}
	{
		size, err := m.UnliquidatedCollateralAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	{
		size, err := m.ProtocolLiquidationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size, err := m.LiquidationBonusAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size, err := m.LiquidatedDebtAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size, err := m.LiquidatedCollateralAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LiquidatedTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LiquidatedTime):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintLiquidation(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x4a
	{
		size := m.LiquidatedPrice.Size()
		i -= size
		if _, err := m.LiquidatedPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.DebtAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.ActualCollateralAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.CollateralAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.DCM) > 0 {
		i -= len(m.DCM)
		copy(dAtA[i:], m.DCM)
		i = encodeVarintLiquidation(dAtA, i, uint64(len(m.DCM)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Debtor) > 0 {
		i -= len(m.Debtor)
		copy(dAtA[i:], m.Debtor)
		i = encodeVarintLiquidation(dAtA, i, uint64(len(m.Debtor)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LoanId) > 0 {
		i -= len(m.LoanId)
		copy(dAtA[i:], m.LoanId)
		i = encodeVarintLiquidation(dAtA, i, uint64(len(m.LoanId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidationRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n10, err10 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time):])
	if err10 != nil {
		return 0, err10
	}
	i -= n10
	i = encodeVarintLiquidation(dAtA, i, uint64(n10))
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.BonusAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.CollateralAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.DebtAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLiquidation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Liquidator) > 0 {
		i -= len(m.Liquidator)
		copy(dAtA[i:], m.Liquidator)
		i = encodeVarintLiquidation(dAtA, i, uint64(len(m.Liquidator)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LiquidationId != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.LiquidationId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintLiquidation(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidation(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Liquidation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLiquidation(uint64(m.Id))
	}
	l = len(m.LoanId)
	if l > 0 {
		n += 1 + l + sovLiquidation(uint64(l))
	}
	l = len(m.Debtor)
	if l > 0 {
		n += 1 + l + sovLiquidation(uint64(l))
	}
	l = len(m.DCM)
	if l > 0 {
		n += 1 + l + sovLiquidation(uint64(l))
	}
	l = m.CollateralAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.ActualCollateralAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.DebtAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.LiquidatedPrice.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LiquidatedTime)
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.LiquidatedCollateralAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.LiquidatedDebtAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.LiquidationBonusAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.ProtocolLiquidationFee.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.UnliquidatedCollateralAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = len(m.LiquidationCet)
	if l > 0 {
		n += 1 + l + sovLiquidation(uint64(l))
	}
	l = len(m.SettlementTx)
	if l > 0 {
		n += 2 + l + sovLiquidation(uint64(l))
	}
	l = len(m.SettlementTxId)
	if l > 0 {
		n += 2 + l + sovLiquidation(uint64(l))
	}
	if m.Status != 0 {
		n += 2 + sovLiquidation(uint64(m.Status))
	}
	return n
}

func (m *LiquidationRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLiquidation(uint64(m.Id))
	}
	if m.LiquidationId != 0 {
		n += 1 + sovLiquidation(uint64(m.LiquidationId))
	}
	l = len(m.Liquidator)
	if l > 0 {
		n += 1 + l + sovLiquidation(uint64(l))
	}
	l = m.DebtAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.CollateralAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = m.BonusAmount.Size()
	n += 1 + l + sovLiquidation(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovLiquidation(uint64(l))
	return n
}

func sovLiquidation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidation(x uint64) (n int) {
	return sovLiquidation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Liquidation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Liquidation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Liquidation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoanId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Debtor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Debtor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DCM", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DCM = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualCollateralAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActualCollateralAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DebtAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidatedPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidatedPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LiquidatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidatedCollateralAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidatedCollateralAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidatedDebtAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidatedDebtAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationBonusAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidationBonusAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolLiquidationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProtocolLiquidationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnliquidatedCollateralAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnliquidatedCollateralAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationCet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationCet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementTx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementTx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementTxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementTxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= LiquidationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidationRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationId", wireType)
			}
			m.LiquidationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liquidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Liquidator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DebtAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BonusAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BonusAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidation = fmt.Errorf("proto: unexpected end of group")
)
