// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: side/farming/farming.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Phase status
type PhaseStatus int32

const (
	PhaseStatus_PHASE_STATUS_UNSPECIFIED PhaseStatus = 0
	PhaseStatus_PHASE_STATUS_PENDING     PhaseStatus = 1
	PhaseStatus_PHASE_STATUS_STARTED     PhaseStatus = 2
	PhaseStatus_PAHSE_STATUS_ENDED       PhaseStatus = 3
)

var PhaseStatus_name = map[int32]string{
	0: "PHASE_STATUS_UNSPECIFIED",
	1: "PHASE_STATUS_PENDING",
	2: "PHASE_STATUS_STARTED",
	3: "PAHSE_STATUS_ENDED",
}

var PhaseStatus_value = map[string]int32{
	"PHASE_STATUS_UNSPECIFIED": 0,
	"PHASE_STATUS_PENDING":     1,
	"PHASE_STATUS_STARTED":     2,
	"PAHSE_STATUS_ENDED":       3,
}

func (x PhaseStatus) String() string {
	return proto.EnumName(PhaseStatus_name, int32(x))
}

func (PhaseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_117d7eb64797c9dd, []int{0}
}

// Staking status
type StakingStatus int32

const (
	StakingStatus_STAKING_STATUS_UNSPECIFIED StakingStatus = 0
	StakingStatus_STAKING_STATUS_STAKED      StakingStatus = 1
	StakingStatus_STAKING_STATUS_UNLOCKED    StakingStatus = 2
	StakingStatus_STAKING_STATUS_UNSTAKED    StakingStatus = 3
)

var StakingStatus_name = map[int32]string{
	0: "STAKING_STATUS_UNSPECIFIED",
	1: "STAKING_STATUS_STAKED",
	2: "STAKING_STATUS_UNLOCKED",
	3: "STAKING_STATUS_UNSTAKED",
}

var StakingStatus_value = map[string]int32{
	"STAKING_STATUS_UNSPECIFIED": 0,
	"STAKING_STATUS_STAKED":      1,
	"STAKING_STATUS_UNLOCKED":    2,
	"STAKING_STATUS_UNSTAKED":    3,
}

func (x StakingStatus) String() string {
	return proto.EnumName(StakingStatus_name, int32(x))
}

func (StakingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_117d7eb64797c9dd, []int{1}
}

// Asset defines the farming asset
type Asset struct {
	// Asset denom
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// Ratio of the reward relative to the total rewards
	RewardRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=reward_ratio,json=rewardRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reward_ratio"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_117d7eb64797c9dd, []int{0}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return m.Size()
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// Phase defines the phase
type Phase struct {
	Id                   uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime            time.Time       `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	Duration             time.Duration   `protobuf:"bytes,3,opt,name=duration,proto3,stdduration" json:"duration"`
	DistributionInterval time.Duration   `protobuf:"bytes,4,opt,name=distribution_interval,json=distributionInterval,proto3,stdduration" json:"distribution_interval"`
	RewardsPerInterval   types.Coin      `protobuf:"bytes,5,opt,name=rewards_per_interval,json=rewardsPerInterval,proto3" json:"rewards_per_interval"`
	LockDurations        []time.Duration `protobuf:"bytes,6,rep,name=lock_durations,json=lockDurations,proto3,stdduration" json:"lock_durations"`
	AllowedAssets        []Asset         `protobuf:"bytes,7,rep,name=allowed_assets,json=allowedAssets,proto3" json:"allowed_assets"`
	Status               PhaseStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=side.farming.PhaseStatus" json:"status,omitempty"`
}

func (m *Phase) Reset()         { *m = Phase{} }
func (m *Phase) String() string { return proto.CompactTextString(m) }
func (*Phase) ProtoMessage()    {}
func (*Phase) Descriptor() ([]byte, []int) {
	return fileDescriptor_117d7eb64797c9dd, []int{1}
}
func (m *Phase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Phase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Phase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Phase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phase.Merge(m, src)
}
func (m *Phase) XXX_Size() int {
	return m.Size()
}
func (m *Phase) XXX_DiscardUnknown() {
	xxx_messageInfo_Phase.DiscardUnknown(m)
}

var xxx_messageInfo_Phase proto.InternalMessageInfo

func (m *Phase) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Phase) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *Phase) GetDuration() time.Duration {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Phase) GetDistributionInterval() time.Duration {
	if m != nil {
		return m.DistributionInterval
	}
	return 0
}

func (m *Phase) GetRewardsPerInterval() types.Coin {
	if m != nil {
		return m.RewardsPerInterval
	}
	return types.Coin{}
}

func (m *Phase) GetLockDurations() []time.Duration {
	if m != nil {
		return m.LockDurations
	}
	return nil
}

func (m *Phase) GetAllowedAssets() []Asset {
	if m != nil {
		return m.AllowedAssets
	}
	return nil
}

func (m *Phase) GetStatus() PhaseStatus {
	if m != nil {
		return m.Status
	}
	return PhaseStatus_PHASE_STATUS_UNSPECIFIED
}

// Staking defines the staking
type Staking struct {
	Id              uint64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PhaseId         uint64                      `protobuf:"varint,2,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	Address         string                      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount          types.Coin                  `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount"`
	LockDuration    time.Duration               `protobuf:"bytes,5,opt,name=lock_duration,json=lockDuration,proto3,stdduration" json:"lock_duration"`
	LockMultiplier  cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=lock_multiplier,json=lockMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"lock_multiplier"`
	EffectiveAmount types.Coin                  `protobuf:"bytes,7,opt,name=effective_amount,json=effectiveAmount,proto3" json:"effective_amount"`
	StartTime       time.Time                   `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	Status          StakingStatus               `protobuf:"varint,9,opt,name=status,proto3,enum=side.farming.StakingStatus" json:"status,omitempty"`
}

func (m *Staking) Reset()         { *m = Staking{} }
func (m *Staking) String() string { return proto.CompactTextString(m) }
func (*Staking) ProtoMessage()    {}
func (*Staking) Descriptor() ([]byte, []int) {
	return fileDescriptor_117d7eb64797c9dd, []int{2}
}
func (m *Staking) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Staking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Staking.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Staking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staking.Merge(m, src)
}
func (m *Staking) XXX_Size() int {
	return m.Size()
}
func (m *Staking) XXX_DiscardUnknown() {
	xxx_messageInfo_Staking.DiscardUnknown(m)
}

var xxx_messageInfo_Staking proto.InternalMessageInfo

func (m *Staking) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Staking) GetPhaseId() uint64 {
	if m != nil {
		return m.PhaseId
	}
	return 0
}

func (m *Staking) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Staking) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *Staking) GetLockDuration() time.Duration {
	if m != nil {
		return m.LockDuration
	}
	return 0
}

func (m *Staking) GetEffectiveAmount() types.Coin {
	if m != nil {
		return m.EffectiveAmount
	}
	return types.Coin{}
}

func (m *Staking) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *Staking) GetStatus() StakingStatus {
	if m != nil {
		return m.Status
	}
	return StakingStatus_STAKING_STATUS_UNSPECIFIED
}

// TotalStaking defines total staking per phase and denom
type TotalStaking struct {
	PhaseId         uint64     `protobuf:"varint,1,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	Denom           string     `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount          types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
	EffectiveAmount types.Coin `protobuf:"bytes,4,opt,name=effective_amount,json=effectiveAmount,proto3" json:"effective_amount"`
}

func (m *TotalStaking) Reset()         { *m = TotalStaking{} }
func (m *TotalStaking) String() string { return proto.CompactTextString(m) }
func (*TotalStaking) ProtoMessage()    {}
func (*TotalStaking) Descriptor() ([]byte, []int) {
	return fileDescriptor_117d7eb64797c9dd, []int{3}
}
func (m *TotalStaking) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TotalStaking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TotalStaking.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TotalStaking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalStaking.Merge(m, src)
}
func (m *TotalStaking) XXX_Size() int {
	return m.Size()
}
func (m *TotalStaking) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalStaking.DiscardUnknown(m)
}

var xxx_messageInfo_TotalStaking proto.InternalMessageInfo

func (m *TotalStaking) GetPhaseId() uint64 {
	if m != nil {
		return m.PhaseId
	}
	return 0
}

func (m *TotalStaking) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *TotalStaking) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *TotalStaking) GetEffectiveAmount() types.Coin {
	if m != nil {
		return m.EffectiveAmount
	}
	return types.Coin{}
}

func init() {
	proto.RegisterEnum("side.farming.PhaseStatus", PhaseStatus_name, PhaseStatus_value)
	proto.RegisterEnum("side.farming.StakingStatus", StakingStatus_name, StakingStatus_value)
	proto.RegisterType((*Asset)(nil), "side.farming.Asset")
	proto.RegisterType((*Phase)(nil), "side.farming.Phase")
	proto.RegisterType((*Staking)(nil), "side.farming.Staking")
	proto.RegisterType((*TotalStaking)(nil), "side.farming.TotalStaking")
}

func init() { proto.RegisterFile("side/farming/farming.proto", fileDescriptor_117d7eb64797c9dd) }

var fileDescriptor_117d7eb64797c9dd = []byte{
	// 815 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x25, 0x59, 0x92, 0xd7, 0x3f, 0x11, 0xb6, 0x4a, 0x4b, 0xc9, 0x05, 0x6d, 0xf8, 0x14,
	0x04, 0x2d, 0x09, 0x27, 0x87, 0x1e, 0x5b, 0xd9, 0x64, 0x62, 0x25, 0xa9, 0xaa, 0x92, 0x0c, 0x50,
	0xe4, 0x42, 0xac, 0xc8, 0x15, 0xbd, 0x30, 0xa9, 0x15, 0xb8, 0x2b, 0xbb, 0xb9, 0xf7, 0xd6, 0x4b,
	0x8e, 0x7d, 0x90, 0x3e, 0x42, 0x0f, 0x39, 0x06, 0x3d, 0x15, 0x3d, 0xa4, 0x85, 0xfd, 0x08, 0x7d,
	0x81, 0x62, 0x97, 0x4b, 0x5a, 0xb2, 0x0c, 0x54, 0xf5, 0xc9, 0x9e, 0xfd, 0x76, 0xbe, 0x99, 0xf9,
	0xbe, 0x59, 0x0a, 0xf4, 0x18, 0x89, 0xb0, 0x35, 0x41, 0x59, 0x4a, 0xa6, 0x71, 0xf1, 0xd7, 0x9c,
	0x65, 0x94, 0x53, 0xb8, 0x2d, 0x30, 0x53, 0x9d, 0xf5, 0x3a, 0x31, 0x8d, 0xa9, 0x04, 0x2c, 0xf1,
	0x5f, 0x7e, 0xa7, 0x67, 0xc4, 0x94, 0xc6, 0x09, 0xb6, 0x64, 0x34, 0x9e, 0x4f, 0xac, 0x68, 0x9e,
	0x21, 0x4e, 0xe8, 0x54, 0xe1, 0xfb, 0xb7, 0x71, 0x4e, 0x52, 0xcc, 0x38, 0x4a, 0x67, 0x05, 0x41,
	0x48, 0x59, 0x4a, 0x99, 0x35, 0x46, 0x0c, 0x5b, 0x17, 0x47, 0x63, 0xcc, 0xd1, 0x91, 0x15, 0x52,
	0x52, 0x10, 0x74, 0x73, 0x3c, 0xc8, 0x2b, 0xe7, 0x41, 0x0e, 0x1d, 0x32, 0xb0, 0xd1, 0x67, 0x0c,
	0x73, 0xd8, 0x01, 0x1b, 0x11, 0x9e, 0xd2, 0x54, 0xd7, 0x0e, 0xb4, 0x47, 0x9b, 0x6e, 0x1e, 0x40,
	0x1f, 0x6c, 0x67, 0xf8, 0x12, 0x65, 0x51, 0x20, 0x3b, 0xd2, 0xab, 0x02, 0x3c, 0x3e, 0x7a, 0xff,
	0x71, 0xbf, 0xf2, 0xe7, 0xc7, 0xfd, 0xbd, 0x9c, 0x8a, 0x45, 0xe7, 0x26, 0xa1, 0x56, 0x8a, 0xf8,
	0x99, 0xf9, 0x0a, 0xc7, 0x28, 0x7c, 0x6b, 0xe3, 0xf0, 0xf7, 0x5f, 0xbf, 0x04, 0xaa, 0x92, 0x8d,
	0x43, 0x77, 0x2b, 0xa7, 0x71, 0x05, 0xcb, 0xe1, 0xcf, 0x75, 0xb0, 0x31, 0x3a, 0x43, 0x0c, 0xc3,
	0x5d, 0x50, 0x25, 0x91, 0x2c, 0x59, 0x77, 0xab, 0x24, 0x82, 0x27, 0x00, 0x30, 0x8e, 0x32, 0x1e,
	0x88, 0x11, 0x65, 0xb5, 0xad, 0x27, 0x3d, 0x33, 0x9f, 0xdf, 0x2c, 0xe6, 0x37, 0xfd, 0x62, 0xfe,
	0xe3, 0x96, 0xe8, 0xe4, 0xdd, 0x5f, 0xfb, 0x9a, 0xbb, 0x29, 0xf3, 0x04, 0x02, 0xbf, 0x06, 0xad,
	0x42, 0x41, 0xbd, 0x26, 0x29, 0xba, 0x2b, 0x14, 0xb6, 0xba, 0x90, 0x33, 0xfc, 0x22, 0x18, 0xca,
	0x24, 0xf8, 0x03, 0x78, 0x18, 0x11, 0xc6, 0x33, 0x32, 0x9e, 0x8b, 0x38, 0x20, 0x53, 0x8e, 0xb3,
	0x0b, 0x94, 0xe8, 0xf5, 0xf5, 0xd9, 0x3a, 0x8b, 0x0c, 0x03, 0x45, 0x00, 0xbf, 0x07, 0x9d, 0x5c,
	0x08, 0x16, 0xcc, 0x70, 0x76, 0x43, 0xbc, 0xa1, 0x88, 0x95, 0x62, 0xc2, 0x48, 0x53, 0x19, 0x69,
	0x9e, 0x50, 0x32, 0x3d, 0xae, 0x0b, 0x62, 0x17, 0xaa, 0xe4, 0x11, 0xce, 0x4a, 0xca, 0x17, 0x60,
	0x37, 0xa1, 0xe1, 0x79, 0x50, 0x74, 0xcf, 0xf4, 0xc6, 0x41, 0x6d, 0xdd, 0x2e, 0x77, 0x44, 0x6a,
	0x71, 0xce, 0xe0, 0x37, 0x60, 0x17, 0x25, 0x09, 0xbd, 0xc4, 0x51, 0x80, 0xc4, 0x56, 0x30, 0xbd,
	0x29, 0xb9, 0x3e, 0x31, 0x17, 0xd7, 0xd8, 0x94, 0x1b, 0xa3, 0x5a, 0xda, 0x51, 0x09, 0xf2, 0x8c,
	0xc1, 0x23, 0xd0, 0x60, 0x1c, 0xf1, 0x39, 0xd3, 0x5b, 0x07, 0xda, 0xa3, 0xdd, 0x27, 0xdd, 0xe5,
	0x4c, 0xe9, 0xba, 0x27, 0x2f, 0xb8, 0xea, 0xe2, 0xe1, 0x3f, 0x35, 0xd0, 0xf4, 0x38, 0x3a, 0x27,
	0xd3, 0x78, 0x65, 0x1f, 0xba, 0xa0, 0x35, 0x13, 0x29, 0x01, 0x89, 0xe4, 0x36, 0xd4, 0xdd, 0xa6,
	0x8c, 0x07, 0x11, 0xd4, 0x41, 0x13, 0x45, 0x51, 0x86, 0x19, 0x93, 0x26, 0x6f, 0xba, 0x45, 0x08,
	0xbf, 0x02, 0x0d, 0x94, 0xd2, 0xf9, 0x94, 0x97, 0x7e, 0xfd, 0x87, 0xac, 0xea, 0x3a, 0x3c, 0x05,
	0x3b, 0x4b, 0x52, 0x96, 0xb6, 0xac, 0xa1, 0xe4, 0xf6, 0xa2, 0x92, 0xf0, 0x0d, 0x78, 0x20, 0x99,
	0xd2, 0x79, 0xc2, 0xc9, 0x2c, 0x21, 0x38, 0xd3, 0x1b, 0xf7, 0x7d, 0x3a, 0xd2, 0xde, 0x6f, 0x4b,
	0x22, 0xf8, 0x02, 0xb4, 0xf1, 0x64, 0x82, 0x43, 0x4e, 0x2e, 0x70, 0xa0, 0x06, 0x6d, 0xae, 0x37,
	0xe8, 0x83, 0x32, 0xb1, 0x9f, 0x4f, 0xbc, 0xfc, 0xde, 0x5a, 0xf7, 0x7b, 0x6f, 0x4f, 0x4b, 0xcf,
	0x37, 0xa5, 0xe7, 0x7b, 0xcb, 0x9e, 0x2b, 0x6f, 0x6f, 0xb9, 0xfe, 0x9b, 0x06, 0xb6, 0x7d, 0xca,
	0x51, 0x52, 0x58, 0xbf, 0x68, 0xb5, 0xb6, 0x6c, 0x75, 0xf9, 0x6d, 0xaa, 0x2e, 0x7e, 0x9b, 0x6e,
	0x6c, 0xae, 0xfd, 0x3f, 0x9b, 0xef, 0x12, 0xb0, 0x7e, 0x3f, 0x01, 0x1f, 0x5f, 0x82, 0xad, 0x85,
	0x9d, 0x86, 0x9f, 0x03, 0x7d, 0x74, 0xda, 0xf7, 0x9c, 0xc0, 0xf3, 0xfb, 0xfe, 0x6b, 0x2f, 0x78,
	0x3d, 0xf4, 0x46, 0xce, 0xc9, 0xe0, 0xd9, 0xc0, 0xb1, 0xdb, 0x15, 0xa8, 0x83, 0xce, 0x12, 0x3a,
	0x72, 0x86, 0xf6, 0x60, 0xf8, 0xbc, 0xad, 0xad, 0x20, 0x9e, 0xdf, 0x77, 0x7d, 0xc7, 0x6e, 0x57,
	0xe1, 0xa7, 0x00, 0x8e, 0xfa, 0xa7, 0x37, 0x88, 0x33, 0xb4, 0x1d, 0xbb, 0x5d, 0x7b, 0xfc, 0x93,
	0x06, 0x76, 0x96, 0x94, 0x85, 0x06, 0xe8, 0x79, 0x7e, 0xff, 0xe5, 0x60, 0xf8, 0xfc, 0xee, 0xea,
	0x5d, 0xf0, 0xf0, 0x16, 0x2e, 0x42, 0xc7, 0x6e, 0x6b, 0x70, 0x0f, 0x7c, 0xb6, 0x92, 0xfa, 0xea,
	0xbb, 0x93, 0x97, 0xb2, 0x83, 0xbb, 0x40, 0x95, 0x59, 0x3b, 0x7e, 0xf6, 0xfe, 0xca, 0xd0, 0x3e,
	0x5c, 0x19, 0xda, 0xdf, 0x57, 0x86, 0xf6, 0xee, 0xda, 0xa8, 0x7c, 0xb8, 0x36, 0x2a, 0x7f, 0x5c,
	0x1b, 0x95, 0x37, 0x5f, 0xc4, 0x84, 0x9f, 0xcd, 0xc7, 0x66, 0x48, 0x53, 0x4b, 0xec, 0x83, 0xdc,
	0xa6, 0x90, 0x26, 0x32, 0xb0, 0x7e, 0x2c, 0x7f, 0x2f, 0xf9, 0xdb, 0x19, 0x66, 0xe3, 0x86, 0x84,
	0x9f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x14, 0x4a, 0x48, 0x80, 0x4c, 0x07, 0x00, 0x00,
}

func (m *Asset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Asset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Asset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RewardRatio.Size()
		i -= size
		if _, err := m.RewardRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintFarming(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Phase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Phase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Phase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if len(m.AllowedAssets) > 0 {
		for iNdEx := len(m.AllowedAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllowedAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFarming(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.LockDurations) > 0 {
		for iNdEx := len(m.LockDurations) - 1; iNdEx >= 0; iNdEx-- {
			n, err := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.LockDurations[iNdEx], dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.LockDurations[iNdEx]):])
			if err != nil {
				return 0, err
			}
			i -= n
			i = encodeVarintFarming(dAtA, i, uint64(n))
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size, err := m.RewardsPerInterval.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.DistributionInterval, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.DistributionInterval):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintFarming(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Duration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Duration):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintFarming(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x1a
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintFarming(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Staking) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Staking) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Staking) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x48
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintFarming(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x42
	{
		size, err := m.EffectiveAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.LockMultiplier.Size()
		i -= size
		if _, err := m.LockMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	n7, err7 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.LockDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.LockDuration):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintFarming(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFarming(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PhaseId != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.PhaseId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TotalStaking) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TotalStaking) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TotalStaking) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EffectiveAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFarming(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintFarming(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.PhaseId != 0 {
		i = encodeVarintFarming(dAtA, i, uint64(m.PhaseId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFarming(dAtA []byte, offset int, v uint64) int {
	offset -= sovFarming(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Asset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovFarming(uint64(l))
	}
	l = m.RewardRatio.Size()
	n += 1 + l + sovFarming(uint64(l))
	return n
}

func (m *Phase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFarming(uint64(m.Id))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovFarming(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Duration)
	n += 1 + l + sovFarming(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.DistributionInterval)
	n += 1 + l + sovFarming(uint64(l))
	l = m.RewardsPerInterval.Size()
	n += 1 + l + sovFarming(uint64(l))
	if len(m.LockDurations) > 0 {
		for _, e := range m.LockDurations {
			l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(e)
			n += 1 + l + sovFarming(uint64(l))
		}
	}
	if len(m.AllowedAssets) > 0 {
		for _, e := range m.AllowedAssets {
			l = e.Size()
			n += 1 + l + sovFarming(uint64(l))
		}
	}
	if m.Status != 0 {
		n += 1 + sovFarming(uint64(m.Status))
	}
	return n
}

func (m *Staking) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFarming(uint64(m.Id))
	}
	if m.PhaseId != 0 {
		n += 1 + sovFarming(uint64(m.PhaseId))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFarming(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFarming(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.LockDuration)
	n += 1 + l + sovFarming(uint64(l))
	l = m.LockMultiplier.Size()
	n += 1 + l + sovFarming(uint64(l))
	l = m.EffectiveAmount.Size()
	n += 1 + l + sovFarming(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovFarming(uint64(l))
	if m.Status != 0 {
		n += 1 + sovFarming(uint64(m.Status))
	}
	return n
}

func (m *TotalStaking) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PhaseId != 0 {
		n += 1 + sovFarming(uint64(m.PhaseId))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovFarming(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFarming(uint64(l))
	l = m.EffectiveAmount.Size()
	n += 1 + l + sovFarming(uint64(l))
	return n
}

func sovFarming(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFarming(x uint64) (n int) {
	return sovFarming(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Asset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Asset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Asset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Phase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Phase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Phase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Duration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.DistributionInterval, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsPerInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardsPerInterval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockDurations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockDurations = append(m.LockDurations, time.Duration(0))
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&(m.LockDurations[len(m.LockDurations)-1]), dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedAssets = append(m.AllowedAssets, Asset{})
			if err := m.AllowedAssets[len(m.AllowedAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PhaseStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Staking) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Staking: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Staking: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhaseId", wireType)
			}
			m.PhaseId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PhaseId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.LockDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LockMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EffectiveAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= StakingStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TotalStaking) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TotalStaking: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TotalStaking: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhaseId", wireType)
			}
			m.PhaseId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PhaseId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFarming
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFarming
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EffectiveAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFarming(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFarming
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFarming(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFarming
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFarming
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFarming
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFarming
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFarming
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFarming        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFarming          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFarming = fmt.Errorf("proto: unexpected end of group")
)
