syntax = "proto3";
package side.tss;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "side/tss/params.proto";
import "side/tss/tss.proto";

option go_package = "github.com/sideprotocol/side/x/tss/types";

// Query defines the gRPC querier service.
service Query {
    // Params queries the parameters of the module.
    rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
      option (google.api.http).get = "/side/tss/params";
    }

    // DKGRequest queries the dkg request by the given id.
    rpc DKGRequest(QueryDKGRequestRequest) returns (QueryDKGRequestResponse) {
        option (google.api.http).get = "/side/tss/dkg/requests/{id}";
    }

    // DKGRequests queries dkg requests by the given params.
    rpc DKGRequests(QueryDKGRequestsRequest) returns (QueryDKGRequestsResponse) {
        option (google.api.http).get = "/side/tss/dkg/requests";
    }

    // DKGCompletions queries dkg completions by the given dkg request id.
    rpc DKGCompletions(QueryDKGCompletionsRequest) returns (QueryDKGCompletionsResponse) {
        option (google.api.http).get = "/side/tss/dkg/completions/{id}";
    }

    // SigningRequest queries the signing request by the given id.
    rpc SigningRequest(QuerySigningRequestRequest) returns (QuerySigningRequestResponse) {
        option (google.api.http).get = "/side/tss/signing/requests/{id}";
    }

    // SigningRequests queries the signing requests by the given params.
    rpc SigningRequests(QuerySigningRequestsRequest) returns (QuerySigningRequestsResponse) {
        option (google.api.http).get = "/side/tss/signing/requests";
    }

    // ResharingRequest queries the resharing request by the given id.
    rpc ResharingRequest(QueryResharingRequestRequest) returns (QueryResharingRequestResponse) {
        option (google.api.http).get = "/side/tss/resharing/requests/{id}";
    }

    // ResharingRequests queries the resharing requests by the given status.
    rpc ResharingRequests(QueryResharingRequestsRequest) returns (QueryResharingRequestsResponse) {
        option (google.api.http).get = "/side/tss/resharing/requests";
    }

    // ResharingCompletions queries resharing completions by the given request id.
    rpc ResharingCompletions(QueryResharingCompletionsRequest) returns (QueryResharingCompletionsResponse) {
        option (google.api.http).get = "/side/tss/resharing/completions/{id}";
    }
}

message QueryDKGRequestRequest {
    uint64 id = 1;
}

message QueryDKGRequestResponse {
    DKGRequest request = 1;
}

message QueryDKGRequestsRequest {
    string module = 1;
    DKGStatus status = 2;
    cosmos.base.query.v1beta1.PageRequest pagination = 3;
}

message QueryDKGRequestsResponse {
    repeated DKGRequest requests = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryDKGCompletionsRequest {
    uint64 id = 1;
    cosmos.base.query.v1beta1.PageRequest pagination = 2;
}

message QueryDKGCompletionsResponse {
    repeated DKGCompletion completions = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QuerySigningRequestRequest {
    uint64 id = 1;
}

message QuerySigningRequestResponse {
    SigningRequest request = 1;
}

message QuerySigningRequestsRequest {
    string module = 1;
    SigningStatus status = 2;
    cosmos.base.query.v1beta1.PageRequest pagination = 3;
}

message QuerySigningRequestsResponse {
    repeated SigningRequest requests = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryResharingRequestRequest {
    uint64 id = 1;
}

message QueryResharingRequestResponse {
    ResharingRequest request = 1;
}

message QueryResharingRequestsRequest {
    ResharingStatus status = 1;
    cosmos.base.query.v1beta1.PageRequest pagination = 2;
}

message QueryResharingRequestsResponse {
    repeated ResharingRequest requests = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

message QueryResharingCompletionsRequest {
    uint64 id = 1;
    cosmos.base.query.v1beta1.PageRequest pagination = 2;
}

message QueryResharingCompletionsResponse {
    repeated ResharingCompletion completions = 1;
    cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {
}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
    Params params = 1 [(gogoproto.nullable) = false];
}
