syntax = "proto3";
package side.dlc;

import "gogoproto/gogo.proto";
import "google/protobuf/duration.proto";
import "cosmos_proto/cosmos.proto";

option go_package = "github.com/sideprotocol/side/x/dlc/types";

message PriceInterval {
    string price_pair = 1;
    string interval = 2 [
      (cosmos_proto.scalar)  = "cosmos.Dec",
      (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
      (gogoproto.nullable)   = false
    ];
}

// Params defines the parameters for the module.
message Params {
    uint32 price_event_nonce_queue_size = 1;
    repeated PriceInterval price_intervals = 2 [(gogoproto.nullable) = false];
    uint32 date_event_nonce_queue_size = 3;
    google.protobuf.Duration date_interval = 4 [(gogoproto.nullable) = false, (gogoproto.stdduration) = true];
    uint32 lending_event_nonce_queue_size = 5;
    uint32 oracle_participant_base_num = 6;
    uint32 oracle_participant_num = 7;
    uint32 nonce_generation_batch_size = 8;
}
