// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: side/lending/lending.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Status options for a lending pool
type PoolStatus int32

const (
	PoolStatus_ACTIVE   PoolStatus = 0
	PoolStatus_INACTIVE PoolStatus = 1
)

var PoolStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
}

var PoolStatus_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
}

func (x PoolStatus) String() string {
	return proto.EnumName(PoolStatus_name, int32(x))
}

func (PoolStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb4e0b35327359cc, []int{0}
}

type LoanStatus int32

const (
	LoanStatus_Created         LoanStatus = 0
	LoanStatus_DCA_Signed      LoanStatus = 1
	LoanStatus_Repay_Initail   LoanStatus = 2
	LoanStatus_Repay_Confirmed LoanStatus = 3
	LoanStatus_Liquidated      LoanStatus = 4
	LoanStatus_Closed          LoanStatus = 5
)

var LoanStatus_name = map[int32]string{
	0: "Created",
	1: "DCA_Signed",
	2: "Repay_Initail",
	3: "Repay_Confirmed",
	4: "Liquidated",
	5: "Closed",
}

var LoanStatus_value = map[string]int32{
	"Created":         0,
	"DCA_Signed":      1,
	"Repay_Initail":   2,
	"Repay_Confirmed": 3,
	"Liquidated":      4,
	"Closed":          5,
}

func (x LoanStatus) String() string {
	return proto.EnumName(LoanStatus_name, int32(x))
}

func (LoanStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb4e0b35327359cc, []int{1}
}

type LendingPool struct {
	Id             string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Supply         *types.Coin `protobuf:"bytes,2,opt,name=supply,proto3" json:"supply,omitempty"`
	TotalShares    uint64      `protobuf:"varint,3,opt,name=total_shares,json=totalShares,proto3" json:"total_shares,omitempty"`
	BorrowedAmount uint64      `protobuf:"varint,4,opt,name=borrowed_amount,json=borrowedAmount,proto3" json:"borrowed_amount,omitempty"`
	Status         PoolStatus  `protobuf:"varint,5,opt,name=status,proto3,enum=side.lending.PoolStatus" json:"status,omitempty"`
}

func (m *LendingPool) Reset()         { *m = LendingPool{} }
func (m *LendingPool) String() string { return proto.CompactTextString(m) }
func (*LendingPool) ProtoMessage()    {}
func (*LendingPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e0b35327359cc, []int{0}
}
func (m *LendingPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LendingPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LendingPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LendingPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LendingPool.Merge(m, src)
}
func (m *LendingPool) XXX_Size() int {
	return m.Size()
}
func (m *LendingPool) XXX_DiscardUnknown() {
	xxx_messageInfo_LendingPool.DiscardUnknown(m)
}

var xxx_messageInfo_LendingPool proto.InternalMessageInfo

func (m *LendingPool) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LendingPool) GetSupply() *types.Coin {
	if m != nil {
		return m.Supply
	}
	return nil
}

func (m *LendingPool) GetTotalShares() uint64 {
	if m != nil {
		return m.TotalShares
	}
	return 0
}

func (m *LendingPool) GetBorrowedAmount() uint64 {
	if m != nil {
		return m.BorrowedAmount
	}
	return 0
}

func (m *LendingPool) GetStatus() PoolStatus {
	if m != nil {
		return m.Status
	}
	return PoolStatus_ACTIVE
}

type Loan struct {
	VaultAddress      string      `protobuf:"bytes,1,opt,name=vault_address,json=vaultAddress,proto3" json:"vault_address,omitempty"`
	Borrower          string      `protobuf:"bytes,2,opt,name=borrower,proto3" json:"borrower,omitempty"`
	Agency            string      `protobuf:"bytes,3,opt,name=agency,proto3" json:"agency,omitempty"`
	HashLoanSecret    string      `protobuf:"bytes,4,opt,name=hash_loan_secret,json=hashLoanSecret,proto3" json:"hash_loan_secret,omitempty"`
	MaturityTime      uint64      `protobuf:"varint,5,opt,name=maturity_time,json=maturityTime,proto3" json:"maturity_time,omitempty"`
	FinalTimeout      string      `protobuf:"bytes,6,opt,name=final_timeout,json=finalTimeout,proto3" json:"final_timeout,omitempty"`
	CollateralTxIds   []string    `protobuf:"bytes,7,rep,name=collateral_tx_ids,json=collateralTxIds,proto3" json:"collateral_tx_ids,omitempty"`
	CollateralAmount  uint64      `protobuf:"varint,8,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount,omitempty"`
	BorrowAmount      *types.Coin `protobuf:"bytes,9,opt,name=borrow_amount,json=borrowAmount,proto3" json:"borrow_amount,omitempty"`
	Fees              *types.Coin `protobuf:"bytes,10,opt,name=fees,proto3" json:"fees,omitempty"`
	Period            uint32      `protobuf:"varint,11,opt,name=period,proto3" json:"period,omitempty"`
	InterestRate      uint32      `protobuf:"varint,12,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	EventId           string      `protobuf:"bytes,13,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CurrentPrice      uint64      `protobuf:"varint,14,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	AttestationId     string      `protobuf:"bytes,15,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	Cets              string      `protobuf:"bytes,16,opt,name=cets,proto3" json:"cets,omitempty"`
	LoanSecret        string      `protobuf:"bytes,17,opt,name=loan_secret,json=loanSecret,proto3" json:"loan_secret,omitempty"`
	RepayAdaptorPoint string      `protobuf:"bytes,18,opt,name=repay_adaptor_point,json=repayAdaptorPoint,proto3" json:"repay_adaptor_point,omitempty"`
	CreateAt          time.Time   `protobuf:"bytes,19,opt,name=create_at,json=createAt,proto3,stdtime" json:"create_at"`
	Status            LoanStatus  `protobuf:"varint,20,opt,name=status,proto3,enum=side.lending.LoanStatus" json:"status,omitempty"`
}

func (m *Loan) Reset()         { *m = Loan{} }
func (m *Loan) String() string { return proto.CompactTextString(m) }
func (*Loan) ProtoMessage()    {}
func (*Loan) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb4e0b35327359cc, []int{1}
}
func (m *Loan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Loan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Loan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Loan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loan.Merge(m, src)
}
func (m *Loan) XXX_Size() int {
	return m.Size()
}
func (m *Loan) XXX_DiscardUnknown() {
	xxx_messageInfo_Loan.DiscardUnknown(m)
}

var xxx_messageInfo_Loan proto.InternalMessageInfo

func (m *Loan) GetVaultAddress() string {
	if m != nil {
		return m.VaultAddress
	}
	return ""
}

func (m *Loan) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *Loan) GetAgency() string {
	if m != nil {
		return m.Agency
	}
	return ""
}

func (m *Loan) GetHashLoanSecret() string {
	if m != nil {
		return m.HashLoanSecret
	}
	return ""
}

func (m *Loan) GetMaturityTime() uint64 {
	if m != nil {
		return m.MaturityTime
	}
	return 0
}

func (m *Loan) GetFinalTimeout() string {
	if m != nil {
		return m.FinalTimeout
	}
	return ""
}

func (m *Loan) GetCollateralTxIds() []string {
	if m != nil {
		return m.CollateralTxIds
	}
	return nil
}

func (m *Loan) GetCollateralAmount() uint64 {
	if m != nil {
		return m.CollateralAmount
	}
	return 0
}

func (m *Loan) GetBorrowAmount() *types.Coin {
	if m != nil {
		return m.BorrowAmount
	}
	return nil
}

func (m *Loan) GetFees() *types.Coin {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *Loan) GetPeriod() uint32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Loan) GetInterestRate() uint32 {
	if m != nil {
		return m.InterestRate
	}
	return 0
}

func (m *Loan) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Loan) GetCurrentPrice() uint64 {
	if m != nil {
		return m.CurrentPrice
	}
	return 0
}

func (m *Loan) GetAttestationId() string {
	if m != nil {
		return m.AttestationId
	}
	return ""
}

func (m *Loan) GetCets() string {
	if m != nil {
		return m.Cets
	}
	return ""
}

func (m *Loan) GetLoanSecret() string {
	if m != nil {
		return m.LoanSecret
	}
	return ""
}

func (m *Loan) GetRepayAdaptorPoint() string {
	if m != nil {
		return m.RepayAdaptorPoint
	}
	return ""
}

func (m *Loan) GetCreateAt() time.Time {
	if m != nil {
		return m.CreateAt
	}
	return time.Time{}
}

func (m *Loan) GetStatus() LoanStatus {
	if m != nil {
		return m.Status
	}
	return LoanStatus_Created
}

func init() {
	proto.RegisterEnum("side.lending.PoolStatus", PoolStatus_name, PoolStatus_value)
	proto.RegisterEnum("side.lending.LoanStatus", LoanStatus_name, LoanStatus_value)
	proto.RegisterType((*LendingPool)(nil), "side.lending.LendingPool")
	proto.RegisterType((*Loan)(nil), "side.lending.Loan")
}

func init() { proto.RegisterFile("side/lending/lending.proto", fileDescriptor_eb4e0b35327359cc) }

var fileDescriptor_eb4e0b35327359cc = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0x23, 0x45,
	0x10, 0xf5, 0x24, 0x5e, 0xc7, 0x2e, 0x7f, 0x64, 0xd2, 0x59, 0xa1, 0x59, 0x1f, 0x1c, 0xb3, 0x08,
	0xb0, 0x02, 0xcc, 0x90, 0xe5, 0x8e, 0xe4, 0x35, 0x20, 0x59, 0x8a, 0x50, 0x34, 0xb1, 0x38, 0x70,
	0x19, 0xb5, 0xa7, 0x2b, 0x4e, 0x4b, 0x33, 0xd3, 0x43, 0x77, 0x4f, 0x88, 0xff, 0xc5, 0x5e, 0xf9,
	0x47, 0x7b, 0x42, 0x7b, 0xe4, 0x04, 0x28, 0xf9, 0x23, 0xa8, 0x6b, 0xc6, 0xeb, 0xac, 0x84, 0xb4,
	0x27, 0x77, 0xbd, 0xf7, 0xaa, 0xaa, 0xeb, 0xb5, 0x6b, 0x60, 0x6c, 0xa4, 0xc0, 0x28, 0xc3, 0x42,
	0xc8, 0x62, 0xb3, 0xfb, 0x0d, 0x4b, 0xad, 0xac, 0x62, 0x03, 0xc7, 0x85, 0x0d, 0x36, 0x7e, 0xbe,
	0x51, 0x1b, 0x45, 0x44, 0xe4, 0x4e, 0xb5, 0x66, 0x7c, 0xb6, 0x51, 0x6a, 0x93, 0x61, 0x44, 0xd1,
	0xba, 0xba, 0x89, 0xac, 0xcc, 0xd1, 0x58, 0x9e, 0x97, 0x8d, 0x60, 0x92, 0x2a, 0x93, 0x2b, 0x13,
	0xad, 0xb9, 0xc1, 0xe8, 0xee, 0x62, 0x8d, 0x96, 0x5f, 0x44, 0xa9, 0x92, 0x45, 0xcd, 0xbf, 0xfc,
	0xd3, 0x83, 0xfe, 0x65, 0xdd, 0xe2, 0x4a, 0xa9, 0x8c, 0x8d, 0xe0, 0x40, 0x8a, 0xc0, 0x9b, 0x7a,
	0xb3, 0x5e, 0x7c, 0x20, 0x05, 0xbb, 0x80, 0x8e, 0xa9, 0xca, 0x32, 0xdb, 0x06, 0x07, 0x53, 0x6f,
	0xd6, 0x7f, 0xf5, 0x22, 0xac, 0x0b, 0x86, 0xae, 0x60, 0xd8, 0x14, 0x0c, 0x17, 0x4a, 0x16, 0x71,
	0x23, 0x64, 0x9f, 0xc2, 0xc0, 0x2a, 0xcb, 0xb3, 0xc4, 0xdc, 0x72, 0x8d, 0x26, 0x38, 0x9c, 0x7a,
	0xb3, 0x76, 0xdc, 0x27, 0xec, 0x9a, 0x20, 0xf6, 0x25, 0x1c, 0xaf, 0x95, 0xd6, 0xea, 0x77, 0x14,
	0x09, 0xcf, 0x55, 0x55, 0xd8, 0xa0, 0x4d, 0xaa, 0xd1, 0x0e, 0x9e, 0x13, 0xca, 0xbe, 0x85, 0x8e,
	0xb1, 0xdc, 0x56, 0x26, 0x78, 0x36, 0xf5, 0x66, 0xa3, 0x57, 0x41, 0xf8, 0xd4, 0x94, 0xd0, 0x5d,
	0xf9, 0x9a, 0xf8, 0xb8, 0xd1, 0xbd, 0xfc, 0xa3, 0x03, 0xed, 0x4b, 0xc5, 0x0b, 0xf6, 0x19, 0x0c,
	0xef, 0x78, 0x95, 0xd9, 0x84, 0x0b, 0xa1, 0xd1, 0x98, 0x66, 0xa8, 0x01, 0x81, 0xf3, 0x1a, 0x63,
	0x63, 0xe8, 0x36, 0x1d, 0x35, 0x0d, 0xd8, 0x8b, 0xdf, 0xc7, 0xec, 0x13, 0xe8, 0xf0, 0x0d, 0x16,
	0xe9, 0x96, 0x26, 0xe8, 0xc5, 0x4d, 0xc4, 0x66, 0xe0, 0xdf, 0x72, 0x73, 0x9b, 0x64, 0x8a, 0x17,
	0x89, 0xc1, 0x54, 0x63, 0x7d, 0xfb, 0x5e, 0x3c, 0x72, 0xb8, 0x6b, 0x7e, 0x4d, 0xa8, 0xbb, 0x42,
	0xce, 0x6d, 0xa5, 0xa5, 0xdd, 0x26, 0xee, 0x61, 0x68, 0x88, 0x76, 0x3c, 0xd8, 0x81, 0x2b, 0x99,
	0xa3, 0x13, 0xdd, 0xc8, 0x82, 0x67, 0xa4, 0x50, 0x95, 0x0d, 0x3a, 0xf5, 0x3d, 0x09, 0x5c, 0xd5,
	0x18, 0x3b, 0x87, 0x93, 0x54, 0x65, 0x19, 0xb7, 0xa8, 0x9d, 0xf2, 0x3e, 0x91, 0xc2, 0x04, 0x47,
	0xd3, 0xc3, 0x59, 0x2f, 0x3e, 0xde, 0x13, 0xab, 0xfb, 0xa5, 0x30, 0xec, 0xab, 0x0f, 0xb4, 0x8d,
	0xbd, 0x5d, 0xea, 0xec, 0xef, 0x89, 0xc6, 0xe0, 0xef, 0x61, 0x58, 0x0f, 0xbc, 0x13, 0xf6, 0x3e,
	0xf6, 0xcc, 0x83, 0x5a, 0xdf, 0xe4, 0x7f, 0x03, 0xed, 0x1b, 0x44, 0x13, 0xc0, 0xc7, 0xd2, 0x48,
	0xe6, 0x3c, 0x2d, 0x51, 0x4b, 0x25, 0x82, 0xfe, 0xd4, 0x9b, 0x0d, 0xe3, 0x26, 0x72, 0x26, 0xc8,
	0xc2, 0xa2, 0x46, 0x63, 0x13, 0xcd, 0x2d, 0x06, 0x03, 0xa2, 0x07, 0x3b, 0x30, 0xe6, 0x16, 0xd9,
	0x0b, 0xe8, 0xe2, 0x1d, 0x16, 0x36, 0x91, 0x22, 0x18, 0x92, 0x49, 0x47, 0x14, 0x2f, 0x29, 0x3f,
	0xad, 0xb4, 0x76, 0x64, 0xa9, 0x65, 0x8a, 0xc1, 0xa8, 0x76, 0xba, 0x01, 0xaf, 0x1c, 0xc6, 0x3e,
	0x87, 0x11, 0xb7, 0xd6, 0xad, 0x87, 0x95, 0xaa, 0x70, 0x55, 0x8e, 0xa9, 0xca, 0xf0, 0x09, 0xba,
	0x14, 0x8c, 0x41, 0x3b, 0x45, 0x6b, 0x02, 0x9f, 0x48, 0x3a, 0xb3, 0x33, 0xe8, 0x3f, 0x7d, 0xee,
	0x13, 0xa2, 0x20, 0xdb, 0x3f, 0x75, 0x08, 0xa7, 0x1a, 0x4b, 0xbe, 0x4d, 0xb8, 0xe0, 0xa5, 0x55,
	0x3a, 0x29, 0x95, 0x2c, 0x6c, 0xc0, 0x48, 0x78, 0x42, 0xd4, 0xbc, 0x66, 0xae, 0x1c, 0xc1, 0xe6,
	0xd0, 0x4b, 0x35, 0x72, 0x8b, 0x09, 0xb7, 0xc1, 0x29, 0x99, 0x37, 0x0e, 0xeb, 0x65, 0x0e, 0x77,
	0xcb, 0x1c, 0xae, 0x76, 0xcb, 0xfc, 0xba, 0xfb, 0xf6, 0xef, 0xb3, 0xd6, 0x9b, 0x7f, 0xce, 0xbc,
	0xb8, 0x5b, 0xa7, 0xcd, 0x9f, 0xee, 0xc6, 0xf3, 0xff, 0xdb, 0x0d, 0xfa, 0x1f, 0x7e, 0xb0, 0x1b,
	0xe7, 0x5f, 0x00, 0xec, 0x37, 0x86, 0x01, 0x74, 0xe6, 0x8b, 0xd5, 0xf2, 0x97, 0x1f, 0xfd, 0x16,
	0x1b, 0x40, 0x77, 0xf9, 0x73, 0x13, 0x79, 0xe7, 0x39, 0xc0, 0x3e, 0x9b, 0xf5, 0xe1, 0x68, 0x41,
	0x3d, 0x85, 0xdf, 0x62, 0x23, 0x80, 0x1f, 0x16, 0xf3, 0xe4, 0x5a, 0x6e, 0x0a, 0x14, 0xbe, 0xc7,
	0x4e, 0x60, 0x18, 0xd3, 0xdc, 0xcb, 0x42, 0x5a, 0x2e, 0x33, 0xff, 0x80, 0x9d, 0xc2, 0x71, 0x0d,
	0x2d, 0x54, 0x71, 0x23, 0x75, 0x8e, 0xc2, 0x3f, 0x74, 0x79, 0x97, 0xf2, 0xb7, 0x4a, 0x0a, 0xaa,
	0xd3, 0x76, 0xcd, 0x17, 0x99, 0x32, 0x28, 0xfc, 0x67, 0xaf, 0x7f, 0x7a, 0xfb, 0x30, 0xf1, 0xde,
	0x3d, 0x4c, 0xbc, 0x7f, 0x1f, 0x26, 0xde, 0x9b, 0xc7, 0x49, 0xeb, 0xdd, 0xe3, 0xa4, 0xf5, 0xd7,
	0xe3, 0xa4, 0xf5, 0xeb, 0xd7, 0x1b, 0x69, 0x6f, 0xab, 0x75, 0x98, 0xaa, 0x3c, 0x72, 0xc3, 0x91,
	0x33, 0xa9, 0xca, 0x28, 0x88, 0xee, 0xdf, 0x7f, 0x38, 0xed, 0xb6, 0x44, 0xb3, 0xee, 0x10, 0xfd,
	0xdd, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x18, 0x8d, 0x75, 0xd5, 0x55, 0x05, 0x00, 0x00,
}

func (m *LendingPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LendingPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LendingPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.BorrowedAmount != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.BorrowedAmount))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalShares != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.TotalShares))
		i--
		dAtA[i] = 0x18
	}
	if m.Supply != nil {
		{
			size, err := m.Supply.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Loan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Loan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Loan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreateAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreateAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintLending(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x9a
	if len(m.RepayAdaptorPoint) > 0 {
		i -= len(m.RepayAdaptorPoint)
		copy(dAtA[i:], m.RepayAdaptorPoint)
		i = encodeVarintLending(dAtA, i, uint64(len(m.RepayAdaptorPoint)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.LoanSecret) > 0 {
		i -= len(m.LoanSecret)
		copy(dAtA[i:], m.LoanSecret)
		i = encodeVarintLending(dAtA, i, uint64(len(m.LoanSecret)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.Cets) > 0 {
		i -= len(m.Cets)
		copy(dAtA[i:], m.Cets)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Cets)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.AttestationId) > 0 {
		i -= len(m.AttestationId)
		copy(dAtA[i:], m.AttestationId)
		i = encodeVarintLending(dAtA, i, uint64(len(m.AttestationId)))
		i--
		dAtA[i] = 0x7a
	}
	if m.CurrentPrice != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.CurrentPrice))
		i--
		dAtA[i] = 0x70
	}
	if len(m.EventId) > 0 {
		i -= len(m.EventId)
		copy(dAtA[i:], m.EventId)
		i = encodeVarintLending(dAtA, i, uint64(len(m.EventId)))
		i--
		dAtA[i] = 0x6a
	}
	if m.InterestRate != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.InterestRate))
		i--
		dAtA[i] = 0x60
	}
	if m.Period != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.Period))
		i--
		dAtA[i] = 0x58
	}
	if m.Fees != nil {
		{
			size, err := m.Fees.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.BorrowAmount != nil {
		{
			size, err := m.BorrowAmount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLending(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.CollateralAmount != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.CollateralAmount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CollateralTxIds) > 0 {
		for iNdEx := len(m.CollateralTxIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CollateralTxIds[iNdEx])
			copy(dAtA[i:], m.CollateralTxIds[iNdEx])
			i = encodeVarintLending(dAtA, i, uint64(len(m.CollateralTxIds[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.FinalTimeout) > 0 {
		i -= len(m.FinalTimeout)
		copy(dAtA[i:], m.FinalTimeout)
		i = encodeVarintLending(dAtA, i, uint64(len(m.FinalTimeout)))
		i--
		dAtA[i] = 0x32
	}
	if m.MaturityTime != 0 {
		i = encodeVarintLending(dAtA, i, uint64(m.MaturityTime))
		i--
		dAtA[i] = 0x28
	}
	if len(m.HashLoanSecret) > 0 {
		i -= len(m.HashLoanSecret)
		copy(dAtA[i:], m.HashLoanSecret)
		i = encodeVarintLending(dAtA, i, uint64(len(m.HashLoanSecret)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Agency) > 0 {
		i -= len(m.Agency)
		copy(dAtA[i:], m.Agency)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Agency)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintLending(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VaultAddress) > 0 {
		i -= len(m.VaultAddress)
		copy(dAtA[i:], m.VaultAddress)
		i = encodeVarintLending(dAtA, i, uint64(len(m.VaultAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLending(dAtA []byte, offset int, v uint64) int {
	offset -= sovLending(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LendingPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Supply != nil {
		l = m.Supply.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.TotalShares != 0 {
		n += 1 + sovLending(uint64(m.TotalShares))
	}
	if m.BorrowedAmount != 0 {
		n += 1 + sovLending(uint64(m.BorrowedAmount))
	}
	if m.Status != 0 {
		n += 1 + sovLending(uint64(m.Status))
	}
	return n
}

func (m *Loan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VaultAddress)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	l = len(m.Agency)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	l = len(m.HashLoanSecret)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if m.MaturityTime != 0 {
		n += 1 + sovLending(uint64(m.MaturityTime))
	}
	l = len(m.FinalTimeout)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if len(m.CollateralTxIds) > 0 {
		for _, s := range m.CollateralTxIds {
			l = len(s)
			n += 1 + l + sovLending(uint64(l))
		}
	}
	if m.CollateralAmount != 0 {
		n += 1 + sovLending(uint64(m.CollateralAmount))
	}
	if m.BorrowAmount != nil {
		l = m.BorrowAmount.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Fees != nil {
		l = m.Fees.Size()
		n += 1 + l + sovLending(uint64(l))
	}
	if m.Period != 0 {
		n += 1 + sovLending(uint64(m.Period))
	}
	if m.InterestRate != 0 {
		n += 1 + sovLending(uint64(m.InterestRate))
	}
	l = len(m.EventId)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	if m.CurrentPrice != 0 {
		n += 1 + sovLending(uint64(m.CurrentPrice))
	}
	l = len(m.AttestationId)
	if l > 0 {
		n += 1 + l + sovLending(uint64(l))
	}
	l = len(m.Cets)
	if l > 0 {
		n += 2 + l + sovLending(uint64(l))
	}
	l = len(m.LoanSecret)
	if l > 0 {
		n += 2 + l + sovLending(uint64(l))
	}
	l = len(m.RepayAdaptorPoint)
	if l > 0 {
		n += 2 + l + sovLending(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreateAt)
	n += 2 + l + sovLending(uint64(l))
	if m.Status != 0 {
		n += 2 + sovLending(uint64(m.Status))
	}
	return n
}

func sovLending(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLending(x uint64) (n int) {
	return sovLending(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LendingPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LendingPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LendingPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Supply == nil {
				m.Supply = &types.Coin{}
			}
			if err := m.Supply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			m.TotalShares = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalShares |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowedAmount", wireType)
			}
			m.BorrowedAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowedAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PoolStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Loan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLending
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Loan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Loan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaultAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashLoanSecret", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashLoanSecret = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaturityTime", wireType)
			}
			m.MaturityTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaturityTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalTimeout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalTimeout = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralTxIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralTxIds = append(m.CollateralTxIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralAmount", wireType)
			}
			m.CollateralAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollateralAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BorrowAmount == nil {
				m.BorrowAmount = &types.Coin{}
			}
			if err := m.BorrowAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fees == nil {
				m.Fees = &types.Coin{}
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			m.Period = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Period |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestRate", wireType)
			}
			m.InterestRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InterestRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPrice", wireType)
			}
			m.CurrentPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cets = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanSecret", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoanSecret = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepayAdaptorPoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepayAdaptorPoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLending
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLending
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreateAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLending
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= LoanStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLending(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLending
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLending(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLending
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLending
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLending
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLending
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLending
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLending
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLending        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLending          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLending = fmt.Errorf("proto: unexpected end of group")
)
